### ISSUE TITLE
libdisk.so.0.0 - location on ubuntu

### ISSUE THREAD

**Issue by tomse** [keirf/Disk-Utilities#41]
On ubuntu amd64 libdisk.so.0.0 (and symlinks) are installed into /usr/local/lib64
to prevent errors, the correct path it should be installed to is /usr/lib

**Comment by keirf** [comment]
I agree lib64 LIBDIR target is obsolete now. I have just removed it so we install to lib always.
However PREFIX is /usr/local by default so default LIBDIR is /usr/local/lib.
If you want to install to /usr rather than /usr/local then you need to 'make install PREFIX=/usr'.
If you just want to override LIBDIR then 'make install LIBDIR=/usr/lib'.
