### ISSUE TITLE
"format all" fails with "bad format name" error

### ISSUE THREAD

**Issue by philpem** [keirf/Disk-Utilities#54]
If I run:

`disk-analyse -f all <dump-file> <outfile>`

I get the error:

`disk-analyse: error at /usr/local/share/disk-analyse/formats:6: bad format name "all"`

If I specify "amigados", "ibm" or similar, it works fine,

How do I get disk-analyse to scan through all the formats it knows of in sequence?

**Comment by keirf** [comment]
You can't and it's not very useful to be able to since there are some very permissive track-format handlers which will generate lots of false positives. You might want to use 'probe_amiga'? I will remove the 'all' option from the formats file, I missed that when removing support in the code itself.

The only other possibility is a new 'all' mode which lists all matching/accepting formats for each track on the disk?

**Comment by philpem** [comment]
That would actually be quite useful. I do a bit of work with PC/DOS floppies (some copy-protected) and the disk-analyse utility has been pretty good at dragging the data off. But for unknown disks ("I have no idea what this is or if it's a variation on something standard"), a "try everything and tell me what the most likely matches are" would be very useful.

**Comment by keirf** [comment]
Fixed. Use new format `probe_all`. Consider redirecting stderr to /dev/null for prettier output.
